<a href="https://colab.research.google.com/github/seki-kou/bingo/blob/main/bingocard.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import random
import numpy as np

In [7]:
bingo_list=random.sample(range(1,75),25)
bingo_list[12]=0
bingo_array=np.array(bingo_list)
bingo_card=bingo_array.reshape(5,5)

print(bingo_card)

[[37 11 36 60 52]
 [54 61 42 23 17]
 [29 51  0 40 45]
 [67 18 31 27 47]
 [56 68 58 19 43]]
